settings:
  commonmark: true
  emphasis: _
  strong: '*'
  bullet: '-'
  incrementListMarker: true
  listItemIndent: mixed
  fences: true
plugins:
  - remark-preset-lint-recommended
  - remark-frontmatter
  - - remark-lint-emphasis-marker
  - - remark-lint-strong-marker
  - - remark-lint-unordered-list-marker-style
    - '-'
  - - remark-lint-ordered-list-marker-value
    - ordered
  - - remark-lint-code-block-style
    - fenced
  - - remark-lint-list-item-indent
    - false
